[tool.poetry]
name = "study"
version = "0.1.0"
description = ""
authors = ["Victor <vitor.passos@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
kagglehub = "^0.3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
