[tool.poetry]
name = "17-class-"
version = "0.1.0"
description = ""
authors = ["Victor <vitor.passos@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.37"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
